server:
  port: 6100

spring:
  application:
    name: gulimall-pms
  datasource:
    username: root
    password: admin.001
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.80.154:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

